#!/usr/bin/env python3
"""
Utility to convert prompts.toml to JavaScript format

This script reads the prompts.toml file and generates a JavaScript file
with equivalent template objects using backticks for multi-line strings
and ${} for variable substitution.
"""

import os
import sys
import tomllib
import json
from typing import Dict, Any


def escape_js_string(text: str) -> str:
    """Escape special characters in JavaScript template literals"""
    result = text

    # Keep Python format placeholders {} as-is for consistency with prompts.toml
    # Handle the special case of double braces {{ }} in JSON examples
    result = result.replace("{{", "{")
    result = result.replace("}}", "}")

    # Escape backticks in the content
    result = result.replace("`", "\\`")

    return result


def convert_dict_to_js_object(data: Dict[str, Any], indent: int = 0) -> str:
    """Convert a Python dictionary to JavaScript object notation"""
    lines = []
    indent_str = "  " * indent

    for key, value in data.items():
        if isinstance(value, dict):
            if "template" in value:
                # This is a template object
                template = escape_js_string(value["template"].strip())
                lines.append(f"{indent_str}{key}: {{")
                lines.append(f"{indent_str}  template: `{template}`,")
                lines.append(f"{indent_str}}},")
            else:
                # This is a nested object
                lines.append(f"{indent_str}{key}: {{")
                lines.append(convert_dict_to_js_object(value, indent + 1))
                lines.append(f"{indent_str}}},")
        elif isinstance(value, str):
            # Regular string property
            escaped_value = value.replace("`", "\\`").replace("\\", "\\\\")
            lines.append(f"{indent_str}{key}: `{escaped_value}`,")
        else:
            # Other types (numbers, booleans, etc.)
            lines.append(f"{indent_str}{key}: {json.dumps(value)},")

    return "\n".join(lines)


def convert_toml_to_js(toml_file: str, js_file: str) -> bool:
    """Convert TOML prompts file to JavaScript format"""

    # Check if input file exists
    if not os.path.exists(toml_file):
        print(f"Error: Input file '{toml_file}' not found")
        return False

    try:
        # Load TOML file
        with open(toml_file, "rb") as f:
            toml_data = tomllib.load(f)

        print(f"Loaded {len(toml_data)} categories from {toml_file}")

        # Generate JavaScript content
        js_content = f"""// Auto-generated from {toml_file}
// Do not edit this file directly - run utils/prompt_convert.py instead

const prompts = {{
{convert_dict_to_js_object(toml_data, 1)}
}};

export default prompts;
"""

        # Write JavaScript file
        with open(js_file, "w", encoding="utf-8") as f:
            f.write(js_content)

        print(f"Successfully converted to {js_file}")
        return True

    except Exception as e:
        print(f"Error converting file: {str(e)}")
        return False


def main():
    """Main function"""
    toml_file = "public/prompts.toml"
    js_file = "src/prompts.js"

    # Check command line arguments
    if len(sys.argv) > 1:
        toml_file = sys.argv[1]
    if len(sys.argv) > 2:
        js_file = sys.argv[2]

    print(f"Converting {toml_file} to {js_file}")

    # Perform conversion
    success = convert_toml_to_js(toml_file, js_file)

    if success:
        print("\n✅ Conversion completed successfully!")
        print(f"Run this script again whenever you update {toml_file}")
    else:
        print("\n❌ Conversion failed!")
        sys.exit(1)


if __name__ == "__main__":
    main()
