// Auto-generated from public/prompts.toml
// Do not edit this file directly - run utils/prompt_convert.py instead

const prompts = {
  landmarks: {
    title: `Landmark Discovery`,
    description: `Prompts for discovering and describing landmarks`,
    discovery: {
      template: `Generate a list of world-famous landmarks and points of interest near {location_name}.  
Focus ONLY on the most notable landmarks within approximately {radius} kilometers.

For each landmark, return:
- 'name': the most relevant and identifiable name to show on a map, and nothing else
- 'local': landmark local name in the native language of its country, used on its Wiki page
- 'description': a brief but informative summary (2-3 sentences, max 100 words)
- 'location': where is the landmark (district, city/region, state/province, country), not street address
- 'lat': landmark's latitude
- 'lon': landmark's longitude
- 'type': what's kind of landmark (Historical, Natural, Cultural, Architecture, Tourist attraction, etc)
- 'name2': landmark and location names (space delimited) in my secondary locale: zh-HK

Return ONLY the top 3 most important and interesting landmarks, ordered by relevance.

Format the response as a valid JSON object with a "landmarks" field containing an array of objects.
Each object should have the fields shown above.  Respond in my primary locale code: {locale}

Example format:
{
  "landmarks": [
    {
      "name": "Golden Gate Bridge",
      "local": "Golden Gate Bridge",
      "description": "An iconic symbol of San Francisco, the Golden Gate Bridge is a stunning suspension bridge",
      "location": "San Francisco, California, United States",
      "lat": 37.775,
      "lon": -122.419,
      "type": "Tourist attraction",
      "name2": "金門橋 三藩市 加州 美國"
    },
    {
      "name": "Victoria Harbour",
      "local": "維多利亞港",
      "description": "Victoria Harbour is the natural harbour separating Hong Kong Island from the Kowloon Peninsula",
      "location": "Kowloon, Hong Kong",
      "lat": 22.2968,
      "lon": 114.1694,
      "type": "觀光景點",
      "name2": "維多利亞港 九龍 香港"
    }
  ]
}`
    },
    selector: {
      template: `Please select the top 3 most interesting landmarks from the following list:

{places_a}
---

Then recommend 3 additional important landmarks nearby, but NOT on the list above.

For each of the six landmarks, return:
- 'name': the most relevant and identifiable name to show on a map, and nothing else
- 'local': landmark local name in the native language of its country, used on its Wiki page
- 'description': a brief but informative summary (2-3 sentences, max 100 words)
- 'location': where is the landmark (district, city/region, state/province, country), not street address
- 'lat': landmark's latitude
- 'lon': landmark's longitude
- 'type': what's kind of landmark (Historical, Natural, Cultural, Architecture, Tourist attraction, etc)
- 'name2': landmark and location names (space delimited) in my secondary locale: zh-HK

Format the response as a valid JSON object with a "landmarks" field containing an array of objects.
Each object should have the fields shown above.  Respond in my primary locale code: {locale}

Example format:
{
  "landmarks": [
    {
      "name": "Golden Gate Bridge",
      "local": "Golden Gate Bridge",
      "description": "An iconic symbol of San Francisco, the Golden Gate Bridge is a stunning suspension bridge",
      "location": "San Francisco, California, United States",
      "lat": 37.775,
      "lon": -122.419,
      "type": "Tourist attraction",
      "name2": "金門橋 三藩市 加州 美國"
    },
    {
      "name": "Victoria Harbour",
      "local": "維多利亞港",
      "description": "Victoria Harbour is the natural harbour separating Hong Kong Island from the Kowloon Peninsula",
      "location": "Kowloon, Hong Kong",
      "lat": 22.2968,
      "lon": 114.1694,
      "type": "觀光景點",
      "name2": "維多利亞港 九龍 香港"
    }
  ]
}`
    },
  },
  system_messages: {
    travel_agent: {
      template: `You are a knowledgeable global travel agent, specializing in “must-see” destinations worldwide.`
    },
    landmark_specialist: {
      template: `You are a knowledgeable global travel agent, specializing in “must-see” destinations worldwide.
You will be provided with a list of popular landmarks within a specific location, ordered by relevance.
Your task is to compile a list of world-famous landmarks and points of interest near that location.`
    },
    location_finder: {
      template: `You are a knowledgeable global travel agent, specializing in “must-see” destinations worldwide.
You will be given a "where is" query to identify what is the name of that specific location.`
    },
  },
  locations: {
    title: `Location Discovery`,
    description: `Prompts for discovering location names from natural language queries`,
    discovery: {
      template: `Where is "{query}"?

Please locate the specific geographic location being asked about:
- 'name': the most relevant and identifiable name to show on a map, and nothing else
- 'local': location local name in the native language of its country, used on its Wiki page
- 'desc': a brief but informative summary (2-3 sentences, max 100 words)
- 'lat': location's latitude
- 'lon': location's longitude
- 'name2': location names in my secondary locale: zh-HK

Format the response as a valid JSON object with the fields shown above.
Respond in my primary locale code: {locale}`
    },
  },
  destinations: {
    title: `Landmark Description`,
    description: `Prompts for generating detailed descriptions of landmarks`,
    history: {
      template: `Generate a brief historical overview of {landmark_name} located in {location_name}.
Include when it was built/established, significant events, and its cultural importance.
Keep the response under 150 words and focus on verified historical facts.`
    },
    architecture: {
      template: `Describe the architectural style and notable design elements of {landmark_name}.
Include information about the architect (if known), unique features, and any
interesting structural aspects. Keep the response under 150 words.`
    },
    visitor_info: {
      template: `Provide concise visitor information for {landmark_name}, including typical 
visiting hours, best time to visit, any entrance fees, and 1-2 insider tips.
Focus on practical information that would be useful for a first-time visitor.
Keep the response under 100 words.`
    },
  },
};

export default prompts;
